### PR TITLE
Update finalise-install to render correctly

### PR DESCRIPTION
**Pull request by settermjd**
This relates to #2554. It also makes some of the changes seen in #2554.

### CODE REVIEW

**Comment by phil-davis** [comment]
@settermjd see issue #2566
It will be good to get this PR working and merged ASAP.

**Comment by settermjd** [comment]
Thanks for chasing this.

**Comment by phil-davis** [comment]
@settermjd please backport

**Comment by settermjd** [comment]
> I don't know the technical stuff about `subs="attributes+"` but let's merge this and verify when it gets published online...

That option ensures that AsciiDoc attributes are substituted in source code blocks. I've just generated the docs again and on quick inspection it seems correct to me.

**Pull request merged**
