### PR TITLE
branch 10.6 with updated .drone.star and site.yml

### PR DESCRIPTION
**Pull request by jnweiger**
Includes todays latest commits from @voroyam and @mschreml, thanks!

Needed for 10.6.0RC2

### CODE REVIEW

**Review by micbar — APPROVED** [review]
LGTM

**Review by dschmidt — APPROVED** [review]

**Review by phil-davis — APPROVED** [review]
Looks OK.

There are plenty of docs issues to finish for 10.6. So if we actually create the branch after merging this PR, then we have to backport every PR to `master`, to `10.6` - but I guess that is life. We have to make the branch some time.

**Comment by dschmidt** [comment]
Well, it can just be merged to master at some point - just the version number changes from this pr need to be reverted on master. Afterwards further merges should be straight forward and don't need to be done for every single commit.

**Comment by jnweiger** [comment]
@phil-davis I've waited 14 days since https://github.com/owncloud/docs/issues/2870#issuecomment-734240745
Sorry to rush that now. I need the PDF be inplace for the preparing the final next Monday.

**Comment by phil-davis** [comment]
> I've waited 14 days since...

Yes, that's fine. The docs work is not making progress at the moment, so we have to move forward with the branching and catch-up the content "later".

**Comment by dschmidt** [comment]
The problem with the missing pdf is most probably that master builds all versioned docs, but it does not build non-master pdfs.

version branches should build and deploy their pdfs, pipelines need to be adjusted for that (and probably backported).

**Comment by dschmidt** [comment]
Fixed in https://github.com/owncloud/docs/pull/2923

as I said: the pdf fix needs backporting for fixing older pdfs upload.

**Pull request merged**
