### PR TITLE
Move release notes and what's new pages to the ROOT module

### LINKED ISSUE #2240: Documentation has two sections called Release Notes
The navigation sidebar at https://doc.owncloud.com/server/10.4/ has 
image

<hr>

The two 'Release Notes' sections are confusing.
If there are two with a purpose, then 
* the first one at the top should talk about the product
* the second one in the Administation Manual would maybe talk about major revisions of the manual?

Currently 
* the first one has a few items about antora (outdated?)
* the second one is about the product.

To resolve the confusion, I suggest to remove the first 'Release Notes' section.
Or move it near the end of the document tree, with a proper heading, that clearly says it describes the documentation itself, and not the product.

### PR DESCRIPTION
**Pull request by settermjd**
The admin and user manuals both had "_What's New_" pages, and the admin manual contained the project's release notes, while the root module contained an outdated set of release notes. This PR moves the release notes from the admin manual to the root module, removes the What's New pages from the admin and user manuals and stores the most up to date copy of the file in the ROOT module.

This fixes #2240.

### CODE REVIEW

**Comment by settermjd** [comment]
Fair point. I'll adjust it accordingly.

**Comment by settermjd** [comment]
Based on your reasons in https://github.com/owncloud/docs/pull/2245#pullrequestreview-346725182, should the What's New page be moved to the admin manual as well?

**Comment by jnweiger** [comment]
> Based on your reasons in [#2245 (review)](https://github.com/owncloud/docs/pull/2245#pullrequestreview-346725182), should the What's New page be moved to the admin manual as well?

The "What's new" section makes sense in the admin manual. (Or in some other PDF) But is not important. For me the important items are:

* Have Release notes in the PDFs
* Don't have "Dummy Releasenotes" first. Releasenotes about the toolchain should go near the end, where contributing to the docs is discussed. That should not be at the start either. That is an advanced thing.

**Comment by settermjd** [comment]
> > Based on your reasons in [#2245 (review)](https://github.com/owncloud/docs/pull/2245#pullrequestreview-346725182), should the What's New page be moved to the admin manual as well?
> 
> The "What's new" section makes sense in the admin manual. (Or in some other PDF) But is not important. For me the important items are:
> 
>     * Have Release notes in the PDFs
> 
>     * Don't have "Dummy Releasenotes" first. Releasenotes about the toolchain should go near the end, where contributing to the docs is discussed. That should not be at the start either. That is an advanced thing.

Makes sense to me.

**Pull request merged**
