### PR TITLE
Change depreacted images/paragraphs, add a note for read only tag list

### PR DESCRIPTION
**Pull request by JanAckermann**
* Replaced deprecated images
* Replaced deprecated paragraphs
* Add a note for the new tag list

### CODE REVIEW

**Comment by mmattel** [comment]
You have deleted two image files, but I do not see that the corresponding includes have been removed.
Q1: were these image files orphans? (there is a check script in /bin...)
Q2: if not orphans, we now have broken links somewhere. Needs checking with a BLC (see docs/readme in a subpage for more infos)
Why not updating (and renaming and fixing the link) the files_page-7.png file (if not orphand)?

**Comment by JanAckermann** [comment]
@mmattel No images had been removed 
Github is not the best change viewer for binary files.

1.
image
-  -xx.kb only shows the reduced filesize of the file.
2.
image
- Click on "View File" will show you the image

**Comment by mmattel** [comment]
You are right, GH is not that good in showing binary changes... 😎

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
No backports necessary because it is part of the next ownCloud release.

**Pull request merged**
