### PR TITLE
Update user_auth_ldap.adoc

### PR DESCRIPTION
**Pull request by NannaBarz**
The point was confusing for me. I missed the hint that you have to create/usw a attribute in the active directory not in ownCloud.

### CODE REVIEW

**Comment by voroyam** [comment]
> create/usw

usw? Do you mean use?

**Comment by NannaBarz** [comment]
Yes I meant use, sry.

**Comment by voroyam** [comment]
Okay, you will need to close this PR and open a new one. When Creating PRs we create them to the master branch. Then we can Backport ( take the change and apply it) from the master branch to the relevant branches.

This PR is to the 10.4 branch instead of the master branch.

**Comment by NannaBarz** [comment]
Did it in the 10.4 branch not in the master branch

**Comment by jnweiger** [comment]
Creating doc PRs to master is the correct approach. In this case closing and reopening is simple enough.
But, there is a trick that makes redirecting a PR possible: The EDIT button for editing the subject line also has a select box for the target branch!

**Pull request closed without merging**
