### PR TITLE
drone testing

### PR DESCRIPTION
**Pull request by voroyam**
fixes https://github.com/owncloud/docs/issues/291

### CODE REVIEW

**Comment by mmattel** [comment]
There are a couple of improvements to be made, I will file an additional commit. Will do this asap.

**Comment by mmattel** [comment]
@xoxys @phil-davis I have made an improvement commmit but your help needed. Can you review and add suggestions/commits? We need an introduction text, and on various items I am not sure if things are complete and/or need more descriptive text.

**Comment by mmattel** [comment]
@phil-davis may I ping for your view...

**Comment by voroyam** [comment]
I think as long as the essence of the text is still the same we can merge it as is and then have changes made to it.

**Comment by mmattel** [comment]
Note, pls fix before merging the introduction text as it is currently only a placeholder...

**Comment by voroyam** [comment]
> Note, pls fix before merging the introduction text as it is currently only a placeholder...

why do you need introductory text anyway? It's a developer docs, no one will read the intro text.

**Comment by mmattel** [comment]
In introduction has no dependency of the type or the name of a doc. An introduction tells briefly what the doc is about and what the reader can expect. This is about professionalism.

**Comment by voroyam** [comment]
> In introduction has no dependency of the type or the name of a doc. An introduction tells briefly what the doc is about and what the reader can expect. This is about professionalism.

How about - this document will tell you how to run drone tests locally?

professionalism ist one thing, realism is another. 

I want to get content to the docs. This issue is very old, and needs to be documented.

**Pull request closed without merging**
