### PR TITLE
Update google.adoc

### PR DESCRIPTION
**Pull request by sahero-86**
correction typo in the word beneficial

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]
Thanks for noticing.

**Comment by phil-davis** [comment]
> there is also a broken link from the user (and I also believe) the admin Manual in pdf form. How does this change be arranged?

@mmattel @EParzefall can you respond/investigate please.

**Comment by phil-davis** [comment]
Backport 10.7 PR #3535 
Note: the Google docs were very different in 10.6 branch. The typo was not there, so no backport to 10.6.

**Comment by mmattel** [comment]
> can you respond/investigate please.

done and clarified

**Pull request merged**
