### PR TITLE
update links to owncloud.org/support

### PR DESCRIPTION
**Pull request by michaelstingl**
owncloud.org was merged with owncloud.com. some links need to be re-adjusted

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]
:+1:

**Comment by pmaier1** [comment]
needs backports

**Comment by mmattel** [comment]
> needs backports

pls note to which branches a BP is needed

**Comment by phil-davis** [comment]
Backports:
10.5 #2842 
10.4 #2843 
10.3 #2844

**Pull request merged**
