### PR TITLE
Check CI for 10.2 branch

### PR DESCRIPTION
**Pull request by phil-davis**
It seems to be failing

### CODE REVIEW

**Comment by settermjd** [comment]
@phil-davis, here's what I've found, in relation to https://github.com/owncloud/docs/pull/1160#issuecomment-490490540; The playbook configuration (site.yml) is not consistent across master, 10.0, 10.1, & 10.2. Here's how it looks in the respective branches:

### 10.2

```yaml
content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - '10.1'
    - '10.0'
```

### 10.1

```yaml
content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - master
    - '10.0'
    - '10.2'
```

### 10.0

```yaml
content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - master
    - '10.1'
    - '10.2'
```

### master

```yaml
content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - '10.1'
    - '10.0'
```

From what I can determine, each of these configurations are only partially correct. Here's why. `modules/ROOT/pages/index.adoc` contains the following snippet:

```asciidoc

== ownCloud X Appliance

The ownCloud X Appliance is a complete virtual machine image running ownCloud X, on _Univention Server_.

* xref:master@admin_manual:appliance/index.adoc[ownCloud X Appliance Manual]
```

The last line references `appliance/index.adoc` in the `admin_manual` module, in the `master` branch. That works when the docs are either validated or built from the `master` branch. But, it won't work from any other branch, as `master` isn't listed in any of the content source configurations. As a result, the link above can't be generated, as the referenced branch is not available as a content source.

If, however, the configurations on all branches were changed to the following, then the problem would be resolved:

```yaml
content:
  sources:
  - url: https://github.com/owncloud/docs.git
    branches:
    - master
    - '10.1'
    - '10.0'
```

**Comment by settermjd** [comment]
@tboerger, can you take a look at https://github.com/owncloud/docs/pull/1170#issuecomment-490794283 pls?

**Comment by tboerger** [comment]
10.2 got to add master to the list of branches, master got to add 10.2 to the list of branches, than it should be fine.

**Comment by settermjd** [comment]
It wouldn't make sense to add 10.2 to master until it's released, no, @tboerger?

**Comment by settermjd** [comment]
Just pushed a PR to make the required corrections for 10.2.

**Comment by phil-davis** [comment]
Fixed by #1182

**Pull request closed without merging**
