### PR TITLE
Fix incorrect reference to master in 10.2

### PR DESCRIPTION
**Pull request by settermjd**

### CODE REVIEW

**Comment by micbar** [comment]
@settermjd @tboerger Needs rebase and review.

**Comment by settermjd** [comment]
@tboerger / @micbar - a review when you have time.

**Comment by tboerger** [comment]
I don't get what I need to review. The configs are anyway getting to be a mess :(

**Comment by settermjd** [comment]
@tboerger, in what way are the configs becoming messy? Can you provide an example with comment, please?

**Pull request merged**
