### PR TITLE
Make the doc URL to use "next" when the branch is master

### PR DESCRIPTION
**Pull request by mmattel**
This PR fixes a couple of issues:

- Enable that the master branch will get its own name ("next") in the url like other branches do. This enables CI to delete all former html code automatically that is orphand and no longer used.
- This is the basis for the new setup of search as all branches now have a URL component
- Create a new page only for accessing html/pdf files including all old pdf files. Note, that the old html links are now removed and no longer accessible. This makes it possible to automatically delete ALL old web data shrinking the space used dramatically AND reducing necessary redirects to a minimum.
- Fix and uniform the makepdf script. The same script can now be used in single and multi manual repos. It is parametrisized with a repo dependent file which eases handling
- Fixed all files and folders relevant for the pdf generation
- Have a uniformed naming convention for pdf files
- PDF files generated via CI will be saved on a special location for web access. This location is NOT synced via git. The files there are overwritten as long builds for that branch are made. If a branch is phased out, the files are quasi-static and need to be manually linked in the `Older ownCloud Server Releases` section in `modules/ROOT/pages/releases.adoc` to be accessible. pdf files which are no longer needed have to be deleted by the webserver team and docs has to unlink them
- Any pdf is now accessible on the url via.
`/pdf/server/<branch>_owncloud_<manual-name>_Manual.pdf`
- When using makepdf locally, pdf files are saved to a folder which is .gitignored, safe for any local testing
- Prepare antora.yml to contain branch specific build variables (compared to site.yml which should hold global variables only). This includes an update in makepdf to use variables from any of the both sources.
- Fix that some png files (or other image files) cause issues when generating the pdf. A new piece of SW has been added which is described in the build-the-docs section in readme.md
Also see the referenced issue below, PR is already merged for owncloudci.

Backport to 10.8 and 10.7 necessary

Note, a similar PR is in preperation for docs-client-dektop. This repo can then be used as template for the remaining doc migrations.

Post merging and backporting this PR, we can move all relevant variables from site.yml to antora.yml - which must be done branch by branch (backporting not possible)

### CODE REVIEW

**Comment by xoxys** [comment]
Need to take a closer look next week, but that the PDF files are part of the repo now is definitely wrong :)

**Comment by xoxys** [comment]
Besides that Im ready to merge this PR.

**Review by xoxys — APPROVED** [review]

**Comment by mmattel** [comment]
> I've changed the output dir to build/pdf/

I will update the coding asap and also the instructions file.
Will let you know when the PR is ready.

**Comment by mmattel** [comment]
We can backport this PR to 10.7 and 10.8 with following IMPORTANT note:

After creating the backport to a branch, but before pushing:
* The version in `antora.yml` must be reverted back to the corresponding branch (not `next`!)
* Having that done, we can safely push the backport PR

**Pull request merged**
