### PR TITLE
Document ability to open the file sidebar from a permalink

### LINKED ISSUE #265: Link to open file sidebar from permalink
"http://host/owncloud/f/$fileId?details=$tabId"

This will open the files app, scroll down to the file as before then automatically open the sidebar with the given tab id.

From https://github.com/owncloud/core/pull/32152

cc @DeepDiver1975

@michaelstingl I think you requested something like this for clients so they could link to the versions panel directly. For the versions panel, replace $tabId with "versionsTabView"

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #265 and relates to https://github.com/owncloud/core/pull/32152. It details the ability to open one of three file sidebars (versions, comments, and shares) by using a permalink. I wasn't quite sure where to document this feature. The three locations that it has been documented in this PR seemed the best places (at least so far).

💁‍♂ Only backport to 10.2.

### CODE REVIEW

**Comment by settermjd** [comment]
@michaelstingl, can you provide a description of the new capability pls?

**Comment by michaelstingl** [comment]
> @michaelstingl, can you provide a description of the new capability pls?

sure: https://github.com/owncloud/core/pull/35104

**Comment by settermjd** [comment]
@michaelstingl, do you just need the new capability added to https://doc.owncloud.com/server/developer_manual/core/ocs-capabilities.html#available-capabilities?

**Comment by michaelstingl** [comment]
> @michaelstingl, do you just need the new capability added to https://doc.owncloud.com/server/developer_manual/core/ocs-capabilities.html#available-capabilities?

yes 👍

**Comment by settermjd** [comment]
@michaelstingl, the capability has been documented. Is this PR ready for merge?

**Comment by michaelstingl** [comment]
> @michaelstingl, the capability has been documented. Is this PR ready for merge?

Add a new section below with the explanation?

**Comment by settermjd** [comment]
> > @michaelstingl, the capability has been documented. Is this PR ready for merge?
> 
> Add a new section below with the explanation?

Does a9a3833e869f047e3acf3cf08dce89201792c273 do what you're after?

**Pull request merged**
