### PR TITLE
Move the API code examples into tab blocks

### PR DESCRIPTION
**Pull request by settermjd**
Instead of having each code example be listed one after the next down the page, requiring a lot of reading and searching by the user, this change moves the code examples into tab blocks, greatly compacting the space used. This relates to #1388.

💁‍♂ https://github.com/owncloud/docs-ui/pull/82 needs to be merged before the changes in this PR will render correctly.

### CODE REVIEW

**Comment by michaelstingl** [comment]
@settermjd Looks like it's not properly tabbed yet:

OCS_Share_API____ownCloud_Documentation

I performed those steps:
```
git pull
git checkout 1397-move-api-code-examples-into-tab-blocks
git pull
yarn install
yarn antora
yarn server
yarn serve
```

**Comment by settermjd** [comment]
@michaelstingl, I should have added the note in the description that https://github.com/owncloud/docs-ui/pull/82 needs to be merged, before seeking a review. Without that reviewed and merged, the changes in this PR won't render correctly.

**Comment by michaelstingl** [comment]
@settermjd Hm, this is difficult for me to review. Based on your screenshots in https://github.com/owncloud/docs/issues/1388#issuecomment-509180745 I'd recommend to merge, then fix issues later…

**Comment by settermjd** [comment]
Thanks for the further feedback.

**Pull request merged**
