### PR TITLE
Update system_requirements.adoc

### PR DESCRIPTION
**Pull request by HanaGemela**

### CODE REVIEW

**Comment by mmattel** [comment]
@HanaGemela 
Question, is this a backport of an existing PR? In case pls reference.
If not, why pushing to 10.3 instead of master?

**Comment by HanaGemela** [comment]
@mmattel no, this is the first PR into server docs. I want this to be in the documentation for latest stable release. It can be backported to master and 10.4.
Or maybe we don't need this information in server docs at all as it is maintained in client docs?

**Comment by mmattel** [comment]
FYI, we always file aginst master and the backport to 10.4 or 10.3 ect. Anything else makes the process not smooth and confusing. Only exception are fixes of existing stuff, but this is quite rare. It would be great if we could stick to this scheme.

**Comment by HanaGemela** [comment]
@mmattel OK. I'll close this and create a new PR into master. Who is doing the backporting? Should I do it using backport.sh?

**Comment by mmattel** [comment]
Great, awaiting your new PR :smile:
Reagrding BP, yes, use the script. You have to wait until master is merged as you need the merge reference. (But you also can ask @settermjd for support) It should create automagically the correct header text for GH which makes it easy to identify based on this header the root PR.

**Pull request closed without merging**
