### PR TITLE
added listing instructions

### PR DESCRIPTION
**Pull request by voroyam**
We had a request of having all federated shares listed. I added the queries for it. Wording and format can be improved.

### CODE REVIEW

**Comment by mmattel** [comment]
@voroyam 
Can you describe in more detail what is behind this?

**Comment by voroyam** [comment]
> @voroyam
> Can you describe in more detail what is behind this?

what's not clear?

**Comment by mmattel** [comment]
* More content needs to be added regarding sample output and an explanation of the output
* These are no bash commands, needs description about how to get to the db console
* When do you need this, what is the rationale behind

**Comment by voroyam** [comment]
> * More content needs to be added regarding sample output and an explanation of the output

why? as it is the new content provides 2 easy to use and understand commands for admins to list federated shares.

> * These are no bash commands, needs description about how to get to the db console

this is a admin manual, for admins, in the federated sharing configuration section.

> * When do you need this, what is the rationale behind

I wrote it in my initial description, and it's in the title - To list federated shares.


This is a PR review in order to review the changes I want to make, these are not crucial changes but changes to make life easier for ownCloud admins. If you want to add extra content on top of what I propose - PR welcome.

**Comment by mmattel** [comment]
> If you want to add extra content on top of what I propose - PR welcome.

Wrong, you fix the content initially with the data requested

**Comment by voroyam** [comment]
> > If you want to add extra content on top of what I propose - PR welcome.
> 
> Wrong, you fix the content initially with the data requested. No merging before fix.

Wrong. I added content, not fixed content. You want more content - you do it.

**Review by mmattel — APPROVED** [review]
👍 
As discussed, backports to 10.6 and 10.7

**Pull request merged**
