### PR TITLE
Run cronjob in quiet mode

### PR DESCRIPTION
**Pull request by xelan**
Avoids output of progress in the cronjob, which is subsequently sent during every run if cron mailing is enabled.

The `--` separator is necessary, as otherwise the `-q` option would be passed to the PHP executable instead of the `occ` script.

### CODE REVIEW

**Comment by xelan** [comment]
#1983 seems related :smile:

**Comment by settermjd** [comment]
@xelan, thanks for the contribution. I'll check it out and give a :+1: afterward, all being well.

**Comment by xelan** [comment]
If occ is run directly without `php -f` (i.e. just `php occ` as in your example) the separator is not needed, and would be passed to the occ script literally.

Please try the full command from the PR.
```bash
php -f /path/to/your/owncloud/occ -- -q system:cron
```

**Comment by xelan** [comment]
Apparently both ways work, either `php -f /path/to/occ` with the separator or `php /path/to/occ` without it.

**Comment by settermjd** [comment]
I hear what you're saying, but that approach isn't the recommended way used throughout the docs to call `occ`. Why do you call it using the `-f` switch?

**Comment by settermjd** [comment]
Thanks for clarifying that it was already documented that way. A large cleanup of the examples in the documentation was conducted about a month ago, and this must have been missed. I'll use that example to check for any others.

**Comment by xelan** [comment]
Ah ok, thank you very much!

**Comment by settermjd** [comment]
Closing, as the changes in #2004 negate the changes in this PR. Thanks for contributing the PR, though, @xelan.

**Comment by xelan** [comment]
Thank you very much for addressing this issue so promptly and your fixes, @settermjd!

**Pull request closed without merging**
