### PR TITLE
Added new metrics documentation.

### PR DESCRIPTION
**Pull request by EParzefall**
I've cleaned up my old branch (hopefully!), here's a new one.
This obsoletes PR #3200.

### CODE REVIEW

**Review by jnweiger — APPROVED** [review]
LGTM

**Comment by EParzefall** [comment]
@phil-davis @pmaier1 do you want to backport this new metrics doc to 10.6?

**Comment by mmattel** [comment]
@EParzefall you merged a bit too early, there was still work to be done...
@jnweiger I know you are eager to get things forward, but approving too early can create double work. I guess that you did not made a build to test upfront approval...

For the next PR´s, pls be a bit more patient for a proper review. Thanks

@pmaier1 @phil-davis this can only be backported to the corresponding branches if it the metrics app is already available for those (10.5 and/or 10.6). Can you pls tell?

**Comment by jnweiger** [comment]
@mmattel yes, I was again eager to get stuff in. :-)
On the unmerged PR, we got a clean drone run https://drone.owncloud.com/owncloud/docs/9682 
But now after merging drone explodes with 
```
$ antora --stacktrace generate --cache-dir cache --redirect-facility disabled --generator ./generator/xref-validator.js --clean --fetch --attribute format=html site.yml --fetch
Error: Unknown TypeError: See cause (url: https://github.com/owncloud/client.git)
    at transformGitCloneError (/drone/src/node_modules/@antora/content-aggregator/lib/aggregate-content.js:794:22)
    at git.clone.then.then.catch (/drone/src/node_modules/@antora/content-aggregator/lib/aggregate-content.js:184:17)
Caused by: TypeError: Cannot read property 'length' of undefined
    at Inflate.push (/drone/src/node_modules/isomorphic-git/node_modules/pako/lib/inflate.js:218:30)
    at listpack (/drone/src/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:3230:16)
```
It seems that drone does not have exactly the same setup for its docs-validate step when preparing for the uploads. That should not be the case.

**Comment by mmattel** [comment]
The issue seems to be somewhere in cloning the repo `https://github.com/owncloud/client.git`.
Can you delete (if exists) in docker the contents of `cache/content/` (location of the cloned manuals like client ect)? 
I have seen that on my local dev env, that I have to do that occasionally and I have not found a reason for

**Comment by jnweiger** [comment]
In the drone environment we have no access to caches.
I triggered a rebuild of the failed drone, now it passes! Nothing to fix on our sides.

**Comment by mmattel** [comment]
Based on chats in talk with @jnweiger, Metrics will be announced soon. Dependent on the ownCloud server requirements for Metrics, backports of this and #3218 may be necessary in the sort oder #3217 then #3218

**Pull request merged**
