### PR TITLE
Add Secure View sharing note

### PR DESCRIPTION
**Pull request by mrow4a**
includes note on limitations of secure view when sharing with multiple groups and users

### CODE REVIEW

**Comment by mrow4a** [comment]
@pmaier1 is this limitation accepted or there should be fix for it implemented?

**Comment by mmattel** [comment]
Q: does this needs backporting and if to which releases?

**Comment by pmaier1** [comment]
> @pmaier1 is this limitation accepted or there should be fix/feature for it implemented?

As discussed, let's keep the limitation for now and document it.

**Comment by mrow4a** [comment]
@mmattel just had a discussion with @pmaier1 and limitation is accepted until further request. Thus it would go into 10.X documentation until resolved in some release.

Seems we will not have such limitation in new roles/ocis architecture. What was agreed to maybe try to have share corner case resolved to enable sharing without validation failing in multi-group share scenario.

**Comment by mmattel** [comment]
@phil-davis @EParzefall mind to do a language check?

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
