### PR TITLE
Add a series of filetype-specific Markfile validation targets

### PR DESCRIPTION
**Pull request by settermjd**
To continue improving the DocOps functionality of the project, I'm adding this change that adds four new targets. The targets add linting support for `XML`, `YAML`, `JSON`, and `PHP` files.

### CODE REVIEW

**Comment by mmattel** [comment]
There should be a help text for each new make command.

When running the example below, I get the following output.
It would be better to show an error text that a component is not installed instead of running thru it and throw errors...
```
make validate-xml
Validating all XML example files
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
find: ‘xmllint’: No such file or directory
```

**Comment by settermjd** [comment]
That's odd. The test should prevent that. Can you pull the branch again and retry?

**Comment by mmattel** [comment]
> Can you pull the branch again and retry?

I updated local master and created a local branch of yours afterwards, just before the tests I made and commented. The branch shows equal to origin...
After installing the library for xmllint, it worked, see my help text note for improvements.

**Comment by settermjd** [comment]
Odd, I never had that experience. Thanks for the input though.

**Pull request merged**
