### PR TITLE
add examples

### PR DESCRIPTION
**Pull request by voroyam**
fixes https://github.com/owncloud/docs/issues/1751

### CODE REVIEW

**Comment by settermjd** [comment]
Here's an example of how the revised formatting renders.

table-example

**Comment by voroyam** [comment]
Absolutely. Thank you for the help.

**Comment by voroyam** [comment]
Does this has to be backported?

**Comment by settermjd** [comment]
> Absolutely. Thank you for the help.

yw.

**Comment by settermjd** [comment]
> Does this has to be backported?

I believe so, yes. I'll take care of that.

**Pull request merged**
