### PR TITLE
Name Change of the Server Documentation for WND

### PR DESCRIPTION
**Pull request by voroyam**
to better distinguish it from the Appliance doc and the upcoming quick guide doc.

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
I guess backporting to 10.6 and 10.5 necessary

**Comment by phil-davis** [comment]
There are 2 PRs about to be merged to master. After that, I will rebase this one...

**Comment by phil-davis** [comment]
Rebased - CI is running...

**Comment by phil-davis** [comment]
@voroyam do you want this applied (backported) to 10.6 and/or 10.5 docs branches?

**Pull request merged**
