### PR TITLE
[WIP] product-documentation > file-operations.adoc

### PR DESCRIPTION
**Pull request by michaelstingl**
@pmaier1 @felixboehm 1st approach to document product design and decisions, starting with the basic file operations. (all ownCloud platforms)

### CODE REVIEW

**Comment by michaelstingl** [comment]
> please use [title case](https://www.grammar-monster.com/lessons/capital_letters_title_case.htm) for headers

Good point – thanks for the reminder

**Comment by settermjd** [comment]
Anytime, @michaelstingl.

**Comment by settermjd** [comment]
@michaelstingl, I made a slight revision to your document, mainly around headers. Can you review and provide further information to the document, so that this PR can be reviewed and merged?

**Comment by mmattel** [comment]
`modules/product-documentation-platform`
- Do we really need a new module ?
- The module name is a very complex, cant we find a better fitting one?
- In case, we need additionally changes to make that module and content visible

**Pull request closed without merging**
