### PR TITLE
ownCloud_installation_Ubuntu_20.04

### PR DESCRIPTION
**Pull request by Akidxx**
How to install ownCloud on Ubuntu 20.04

### CODE REVIEW

**Comment by mmattel** [comment]
Hello @Akidxx thanks for your PR !
I am just doing a big rewrite of the manual installation documentation, there is a PR [WIP] you can look at.
For the moment, let´s do not merge that because that should fit in the new one.

**Comment by voroyam** [comment]
This PR is just the update of the existing guide for the installation. The existing guide worked and was used very much by support and customers. This update is necessary.

If you are planing to do a rewrite of something please coordinate with the support team, as we read, use and send out the documentation to users and customers.

You also could just as well post something in the FAQ section of central. There we host user generated content.

**Comment by mmattel** [comment]
@voroyam I am not touching your documents at all - no worry!

**Comment by voroyam** [comment]
Not worried. Just informing you why this PR has been made

**Comment by mmattel** [comment]
@voroyam when looking into the PR mentioned above (https://github.com/owncloud/docs/pull/2958 Improve Manual Installation), your installation guide has not been touched. For better navigation, I have created a sub-nav-level called `Quick Installation Guides` and put the 18.04 document in, pls see the screenshot.
image
When that PR gets merged, the file of this PR should be part of that level and get a nav entry. 
I hope you are fine with.

**Pull request closed without merging**
