### PR TITLE
fix pdf links for old server version

### PR DESCRIPTION
**Pull request by xoxys**
Fixes PDF links for older server versions and adds missing versions.

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
This needs backporting to 10.6 and 10.5

**Comment by xoxys** [comment]
Not very familiar with the docs backporting process. Can someone of you take care?

**Comment by mmattel** [comment]
> Not very familiar with the docs backporting process. Can someone of you take care?

Just merge, will do BP in the evening

**Comment by xoxys** [comment]
Thanks!

**Pull request merged**
