### PR TITLE
Third party apps in package installation

### PR DESCRIPTION
**Pull request by voroyam**
Third party apps in package installation

fixes https://github.com/owncloud/docs/issues/1376

I removed the link in "Disable" because the new link already covers the disabling of the apps.

### CODE REVIEW

**Comment by ho4ho** [comment]
Also link https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/apps_supported.adoc ?

**Comment by voroyam** [comment]
> Also link https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/apps_supported.adoc ?

context?

**Comment by ho4ho** [comment]
> > Also link https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/installation/apps_supported.adoc ?
> 
> context?

Mean 533d425ee95656bd533065537021e14c111f61e4 from #1549

**Comment by voroyam** [comment]
why though?

**Pull request merged**
