### PR TITLE
Add new picture security warnings

### PR DESCRIPTION
**Pull request by mschreml**
Issue #2351 

Added new picture with all security warnings including cron. Cron was missing in the old picture.

Backport needed for 

10.6
10.5
10.4

### CODE REVIEW

**Comment by mmattel** [comment]
@mschreml 
Updating a picture is a good idea if the old picture is outdated and needs to be replaced. :smile:

I see that you just have identified that your steps had a missing pice. Adopting the link to the image...
You corrected it - nice

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
@phil-davis I am just helping @mschreml with a git how to. If we need more support we will let you know :smile:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@mmattel should I merge this when CI passes?

**Comment by mmattel** [comment]
no, we are training how to squash before 😅

**Pull request merged**
