### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by hurradieweltgehtunter**
See https://github.com/owncloud/core/pull/38821

### CODE REVIEW

**Comment by mmattel** [comment]
If Ci gets green, we have to check if the image sizes are the same because of png -> jpg via a local build. Just for security that nothing looks different (beside the content).

**Comment by mmattel** [comment]
Note, no backporting as this is for 10.8 only

**Comment by mmattel** [comment]
@hurradieweltgehtunter 
I ran a local build and I am not happy with the images - they are blurry...
This is well seeable and does not look good.
image
Beside that, I will take the chance to resize the images in the wizard a bit, to the same size we have in the user section (75%) after there are non-blurry images uploaded.

**Comment by hurradieweltgehtunter** [comment]
I noted the very small resolution of the original images but did not change anything. 
I can reupload with bigger sizes

**Comment by mmattel** [comment]
> I can reupload with bigger sizes

@hurradieweltgehtunter please do so, build resizing is not a problem. Just let me know when you are done and I will check 😄

**Comment by hurradieweltgehtunter** [comment]
> > I can reupload with bigger sizes
> 
> @hurradieweltgehtunter please do so, image resizing for the build is not a problem. Just let me know when you are done and I will check 😄

Already done

**Review by mmattel — APPROVED** [review]

**Pull request merged**
