### PR TITLE
Document how to enable images in asciidoc preview pane

### PR DESCRIPTION
**Pull request by settermjd**
One of the members of the Antora/Users channel mentioned that he had found out how to enable images in the IntelliJ preview pane, so I created this PR to update the relevant contributor documentation to include that information.

💁‍♂️ This change only applies to Atom and IntelliJ. It doesn't apply to VIM and SublimeText, and I don't know how to do it in VS Code, _yet_.

### CODE REVIEW

**Comment by mmattel** [comment]
Improvememts:
1) have the same „unfortunately“ sentence for both editors
2) use NOTE: for that comment

**Comment by settermjd** [comment]
I can't use an admonition, as it's a Markdown file.

**Comment by settermjd** [comment]
It's not the same sentence. I slightly modified it because of the differences in the respective plugin UIs.

**Comment by mmattel** [comment]
You are right, overseen that, sorry :see_no_evil:

**Pull request merged**
