### PR TITLE
Create nginx_configuration.adoc

### PR DESCRIPTION
**Pull request by voroyam**
trying to remove the cached web page via putting a empty page instead.

### CODE REVIEW

**Comment by tboerger** [comment]
This page is not linked within the documentation anymore. And even the google results should disappear instead of redirect.

**Comment by settermjd** [comment]
A redirect would help ensure that the Google search results disappeared. Alternatively, a link to the correct documentation would be helpful to people who may have the page bookmarked, or who land there because of existing Google search results cache.

**Comment by voroyam** [comment]
@settermjd if you have a better way of fixing the current state - please do. This is my quick fix.

**Comment by settermjd** [comment]
> @settermjd if you have a better way of fixing the current state - please do. This is my quick fix.

As I wrote earlier, I'd either add a page redirect, or a link to the Apache documentation.

**Comment by voroyam** [comment]
If it solves the problem we are having right now - that despite the nginx page on github being gone, the online docs still displays it - you are welcome to do this.

**Comment by settermjd** [comment]
> If it solves the problem we are having right now - that despite the nginx page on github being gone, the online docs still displays it - you are welcome to do this.

Done.

**Pull request merged**
