### PR TITLE
typoe

### PR DESCRIPTION
**Pull request by jnweiger**

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
Thanks for fixing this.
To which branches this needs a backport ?

**Comment by mmattel** [comment]
Btw, nice naming a branch "typoe" fixing a "typo" 🤣

**Comment by jnweiger** [comment]
backport to 10.8 optional, I'd say...
Who cares about speling, these days :upside_down_face:

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backports done.

It is easier to always backport typos/fixes. That reduces the chance of backport conflicts for real future changes.

**Pull request merged**
