### PR TITLE
Remove note about mtime

### PR DESCRIPTION
**Pull request by phil-davis**
`NOTE: ownCloud does not preserve the mtime (modification time) of directories...`

This note is appearing "randomly" in the middle of sections about the various file sharing options.

Maybe it was somewhere else in old docs? Where should it go?

### CODE REVIEW

**Comment by phil-davis** [comment]
@settermjd I'm sure its not completely random :)
Possibly it used to be a note under some other section/paragraph. And so it needs to be moved "back" to wherever it makes more sense.

**Comment by settermjd** [comment]
@phil-d

> @settermjd I'm sure its not completely random :)
> Possibly it used to be a note under some other section/paragraph. And so it needs to be moved "back" to wherever it makes more sense.

Just wanted to be thorough in following this up.

**Comment by settermjd** [comment]
Consequently, I'm not sure where to put it at the moment, but I'll grok the docs for a good spot for it.

**Comment by settermjd** [comment]
One good place to put it might be after the first paragraph in [the retention section of the enterprise files tagging docs](https://github.com/owncloud/docs/blob/master/modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc#retention). Another good place might be in the developer docs for [creating custom storage backends.](https://github.com/owncloud/docs/blob/master/modules/developer_manual/pages/app/advanced/storage-backend.adoc#required-methods), and for creating custom cache backends.

**Pull request merged**
