### PR TITLE
Trigger client migration basic > OIDC

### PR DESCRIPTION
**Pull request by michaelstingl**
## How Has This Been Tested?

```
git clone https://github.com/owncloud/docs.git
cd docs
git checkout oidc/basic-migration
yarn install
yarn antora
yarn serve
```

Test http://localhost:8080/server/admin_manual/configuration/user/oidc/index.html

CleanShot 2020-11-02 at 17 52 32@2x

@pmaier1 could you fix lower-/upper-case, punctuation etc?

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]
thx :+1: needs backports @phil-davis ?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backport to 10.5 is PR #2852

**Comment by phil-davis** [comment]
@michaelstingl 10.4 branch has a quite different https://github.com/owncloud/docs/blob/10.4/modules/admin_manual/pages/configuration/user/oidc/index.adoc - the backport gives conflicts that are not obvious to resolve.

Do we need to get OIDC instructions updated in 10.4 branch?

If so, should it be a copy of everything from 10.5 branch, or?

**Comment by michaelstingl** [comment]
I’d not recommend to run OIDC with pre-10.5 oC. Not relevant from my perspective.

**Comment by mmattel** [comment]
@michaelstingl 
Maybe I am wrong, but the app release for IOS is currently at 11.x but stated in docs with `iOS >= 1.2`
There is a huge gap between those version numbers...

**Comment by pmaier1** [comment]
> @michaelstingl
Maybe I am wrong, but the app release for IOS is currently at 11.x but stated in docs with iOS >= 1.2
There is a huge gap between those version numbers...

The new iOS app does support OIDC since the very beginning. 1.2 was the first public version. By the way, the gap is not so huge :) https://owncloud.com/news/with-owncloud-for-ios-3-8-1-3-really-is-11-4-trust-us/

**Comment by mmattel** [comment]
Thanks a lot for explaining @pmaier1 👍 
I thought in the first moment a number got lost while typing (11.2 --> 1.2) ... :smile:

**Comment by michaelstingl** [comment]
1.0, 1.1, 1.2, 1.3, 11.4 … (we prefixed the 1.4 with additional digit)

**Pull request merged**
