### PR TITLE
Clarify the description of Office Online unlocking

### PR DESCRIPTION
**Pull request by phil-davis**
Maybe writing a more simple sentence will avoid confusion?

I am intending to describe/document more clearly/simply what the required/intended behaviour is. Then of course if the software does not actually do it, then there is a bug to be investigated and fixed.

Will need backport to 10.4 and 10.3

### CODE REVIEW

**Comment by phil-davis** [comment]
@voroyam does this seem clearer?

@DeepDiver1975 IMO this is what happens. Am I correct?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 IMO this is what happens. Am I correct?

yes - this is correct - but I don't get the point on documenting office online server's behavior ..... anyway you for sure have a reason to do so ...

**Comment by phil-davis** [comment]
I am just clarifying and simplifying the existing documentation. The way it is currently written is a bit ambiguous.

**Comment by DeepDiver1975** [comment]
> I am just clarifying and simplifying the existing documentation. The way it is currently written is a bit ambiguous.

no worries @phil-davis - I'm just wondering in a general manner ;-)

**Comment by phil-davis** [comment]
@voroyam @settermjd 
Now it has been found that the issue with files getting left locked after closing them, that issue is a known problem with Office Online and Chrome. IMO we do not need to be document stuff like that - but if someone wants to then it can be done in a separate PR.

Please review this PR to see if the change makes the meaning easier to understand.

**Comment by voroyam** [comment]
Big Thanks for making this PR @phil-davis

**Pull request merged**
