### PR TITLE
Ignore the cache directory

### PR DESCRIPTION
**Pull request by settermjd**
No need to include it.

### CODE REVIEW

**Comment by tboerger** [comment]
```
public/
cache/
**/*.pdf
```

You don't need the `*` :)

**Comment by settermjd** [comment]
@tboerger, I don't? I thought it was necessary to search/glob anywhere in the repo?

**Comment by tboerger** [comment]
Not for gitignore.

**Comment by settermjd** [comment]
Forget my earlier comment, I was, for some reason, referring to the pdf line, not the cache line. That and I misread your comment. .gitignore's now updated.

**Pull request merged**
