### PR TITLE
Remove specific reference to PHP 7.3 in the Ubuntu 18 guide

### PR DESCRIPTION
**Pull request by settermjd**
This relates to #2213, #2214 & #2202.

### CODE REVIEW

**Comment by settermjd** [comment]
> Down at line 53 to 63 there are also explicit mentions of PHP 7.3

Today's just not my day. Thanks.

**Comment by mmattel** [comment]
Oh, you remove the reference to a particular php version but then the document describes how to install php7.3 (which cant be installed in the way as described as the prerequisites for doing it for Ubuntu 18.04 have been removed... ???
```
Install the Required Packages

apt install -y \
  apache2 \
  libapache2-mod-php7.3 \
  mariadb-server \
  openssl \
  php-imagick php7.3-common php7.3-curl \
  php7.3-gd php7.3-imap php7.3-intl \
  php7.3-json php7.3-mbstring php7.3-mysql \
  php-ssh2 php7.3-xml php7.3-zip \
  php-apcu php-redis redis-server \
  wget
```

Just read the comments in the other PR why the removed commands are necessary - please.

**Comment by settermjd** [comment]
> Oh, you remove the reference to a particular php version but then the document describes how to install php7.3 (which cant be installed in the way as described as the prerequisites for doing it for Ubuntu 18.04 have been removed... ???
> 
> ```
> Install the Required Packages
> 
> apt install -y \
>   apache2 \
>   libapache2-mod-php7.3 \
>   mariadb-server \
>   openssl \
>   php-imagick php7.3-common php7.3-curl \
>   php7.3-gd php7.3-imap php7.3-intl \
>   php7.3-json php7.3-mbstring php7.3-mysql \
>   php-ssh2 php7.3-xml php7.3-zip \
>   php-apcu php-redis redis-server \
>   wget
> ```
> 
> Just read the comments in the other PR why the removed commands are necessary - please.

That is also being removed, as per the comment from @phil-davis.

**Comment by settermjd** [comment]
Just checking that the revised commands work properly. So far, so good.

**Comment by settermjd** [comment]
The commands work as published.

**Comment by phil-davis** [comment]
@settermjd please backport to appropriate branches

**Comment by mmattel** [comment]
👍 as this is now neutral (installs php7.2 per default), I am fine with.

**Pull request merged**
