### PR TITLE
Add missing Redis server to recommended system requirements image

### LINKED ISSUE #2356: Missing Redis server
https://doc.owncloud.com/server/10.4/admin_manual/installation/deployment_recommendations.html#recommended-system-requirements-2

The description says redis server, but there is none on the picture

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #2356.

### CODE REVIEW

**Comment by voroyam** [comment]
can you post a screenshot on those images as I can't open them in github?

**Comment by phil-davis** [comment]
deprecs-2.png

deprecs-2

deprecs-2.odg

Screenshot from 2020-04-15 16-42-36

**Comment by voroyam** [comment]
Thanks @phil-davis :)

**Comment by settermjd** [comment]
Hmmm, wait. Perhaps I should have used Ascii art + asciidoctor-diagram for least vendor lock-in

**Pull request merged**
