### PR TITLE
Changed modules/admin_manual/pages/configuration/user/guests_app.adoc

### PR DESCRIPTION
**Pull request by JanAckermann**
* Removed the enterprise only title
* Changed 'enterprise bundle to enterprise'

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
Backports to? (guess 10.6 and 10.5, or?)

**Comment by phil-davis** [comment]
10.6 and 10.5 is the standard "these days".

@JanAckermann are you making the backport PRs?

**Comment by mmattel** [comment]
...is the standard...
I know, but to aviod errors, we should document it.
Just my 2c

**Comment by JanAckermann** [comment]
@phil-davis  ofc, how is the workflow?

**Comment by mmattel** [comment]
for easiest handling, see: https://doc.owncloud.com/server/developer_manual/general/backporting.html

**Comment by JanAckermann** [comment]
Backport scheduled for the evening :)

**Comment by phil-davis** [comment]
Backports:
10.6 #3112 
10.5 #3113

**Comment by JanAckermann** [comment]
Ooops forgot about it, thank you @phil-davis

**Comment by phil-davis** [comment]
I don't know how we keep track of these. Adding "backport" label to the master PR is not really effective, because the PR is closed and never gets noticed anyway.

**Comment by JanAckermann** [comment]
> I don't know how we keep track of these. Adding "backport" label to the master PR is not really effective, because the PR is closed and never gets noticed anyway.

If someone says, he's after the backporting, but doesn't do it, hard to track.
Blame on me.

**Pull request merged**
