### PR TITLE
removed upload gui option

### PR DESCRIPTION
**Pull request by voroyam**

### CODE REVIEW

**Comment by voroyam** [comment]
I think in the switch from 9 to 10.

**Comment by mmattel** [comment]
@voroyam when deleting a text block containing links to images, please check if these images are used somwhere else and in case they are not, remove the images too to avoid image orpahns.

Finding and fixing orphand images was a nightmare job when migrating from old to new docs...

**Comment by voroyam** [comment]
Good Point. Will check

**Comment by settermjd** [comment]
@voroyam, any chance you can link to the commit where the change was made?

**Comment by voroyam** [comment]
> @voroyam, any chance you can link to the commit where the change was made?

what commit?

**Pull request merged**
