### PR TITLE
updated selinux configuration to reflect apps-external change with 10.2

### PR DESCRIPTION
**Pull request by patrickjahns**
With 10.2 the `apps-external` folder has been made default. 
This pr now changes the selinux configuration to allow http/apache to write to the apps-external folder ( instead of the old apps folder )

### CODE REVIEW

**Comment by mmattel** [comment]
@patrickjahns question, shouldn´t it be added instead replaced?
`apps` is still, as far I understood, also for selinux a valid location

**Comment by settermjd** [comment]
@mmattel, your comment in https://github.com/owncloud/docs/pull/1065#issuecomment-486557915 is exactly what I was thinking. @patrickjahns?

**Comment by patrickjahns** [comment]
@mmattel 
Good question - from my understanding no, as the `apps` folder is read only for ownCloud. 
Modifications should only be made to `apps-external` and thus only there the apache/httpd process would need rw permissions

Thinking a bit more of this now, there seems to be then one exception: `templateeditor` - this will try to save the mail templates within the current active theme. Would need to double check which folder it saves the templates, when the 'default' theme is active to ensure template editor works

**Comment by mmattel** [comment]
Pls keep in mind that `apps-external` is automatically set for new installations only. Not when doing an upgrade. Therefore I propose to keep `apps`.

**Comment by patrickjahns** [comment]
Works for me - maybe add a note about this? As you are correct, old installations will not have this folder by default

**Comment by mmattel** [comment]
My very personal view, I would keep `apps` and add `apps-external`. ownCloud defines what using when and we avoid writing additional notes or description text to clarify things. If it would help, I can do a commit for you.

**Comment by mmattel** [comment]
**NOTE:** Backport only to 10.2, not below...

**Pull request merged**
