### PR TITLE
Fix docs pdf errors

### PR DESCRIPTION
**Pull request by phil-davis**
I noticed in drone: https://drone.owncloud.com/owncloud/docs/6130/1/6
```
Generating version 'master' of the admin manual, dated: November 06, 2019
asciidoctor: ERROR: modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc: line 15: include file not found: /drone/src/modules/admin_manual/pages/_partials/configuration/server/system_command.adoc
Failed to parse formatted text: <img src="/drone/src/modules/admin_manual/assets/images/configuration/server/anti-virus-message-misconfiguration-problem.png" format="png" alt="[Configuration error message: 'Antivirus app is misconfigured or antivirus inaccessible. The antivirus executable could not be found at path '/usr/bin/clamsfcan".]" tmp="false">
Generating version 'master' of the developer manual, dated: November 06, 2019
Generating version 'master' of the user manual, dated: November 06, 2019
```

And when I browse online to https://doc.owncloud.com/server/admin_manual/configuration/server/background_jobs_configuration.html
Then I see `Unresolved include directive in modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc - include::partial$configuration/server/system_command.adoc[]` 

This PR tries to fix those.

### CODE REVIEW

**Comment by phil-davis** [comment]
drone https://drone.owncloud.com/owncloud/docs/6131/1/6
```
+ bin/cli -m
Generating version 'master' of the admin manual, dated: November 06, 2019
Generating version 'master' of the developer manual, dated: November 06, 2019
Generating version 'master' of the user manual, dated: November 06, 2019
```
The log output looks better

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/docs/6140/1/6 has:
```
Generating version 'master' of the admin manual, dated: November 07, 2019
Failed to parse formatted text: <img src="/drone/src/modules/admin_manual/assets/images/configuration/server/anti-virus-message-misconfiguration-problem.png" format="png" alt="[Configuration error message: "Antivirus app is misconfigured or antivirus inaccessible. The antivirus executable could not be found at path '/usr/bin/clamsfcan'".]" tmp="false">
Generating version 'master' of the developer manual, dated: November 07, 2019
Generating version 'master' of the user manual, dated: November 07, 2019
DocumentationPluginsSupport
```
So it still struggles with the combination of quotation marks.

**Comment by settermjd** [comment]
> https://drone.owncloud.com/owncloud/docs/6140/1/6 has:
> 
> ```
> Generating version 'master' of the admin manual, dated: November 07, 2019
> Failed to parse formatted text: [Configuration error message:
> Generating version 'master' of the developer manual, dated: November 07, 2019
> Generating version 'master' of the user manual, dated: November 07, 2019
> DocumentationPluginsSupport
> ```
> 
> So it still struggles with the combination of quotation marks.

Ah, pity. Will fix.

**Comment by settermjd** [comment]
Just reset it to what it was. Thanks for the prompt, @phil-davis.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/docs/6143/1/6 dcos-pdf output looks good.
```
+ bin/cli -m
Generating version 'master' of the admin manual, dated: November 07, 2019
Generating version 'master' of the developer manual, dated: November 07, 2019
Generating version 'master' of the user manual, dated: November 07, 2019
```

**Pull request merged**
