### PR TITLE
Add a section on rate limiting in ownCloud

### LINKED ISSUE #1195: Rate-Limiting
## What Needs to be Documented?
Currently ownCloud deliberately does not provide any form of rate-limiting. The reason being that the product needs to integrate in to different environments with a diverse infrastructure which often already provide a specialized rate-limiting solution (nginx, haproxy, F5 etc.)

## Where Does This Need To Be Documented?
Advanced documentation / Hardening

## Why Should This Change Be Made?
As we offer no rate-limiting out of the box (except brute-force protection) it is possible to overflow the database by mass-creating shares or custom-groups. We should at least have a documentation with rate-limiting recommendations for the customer. For this we should create a list with different routes and their recommended limits. 

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #1195. It adds a section which details how users can get
started with implementing rate limiting in their ownCloud installations.

### CODE REVIEW

**Comment by settermjd** [comment]
@IljaN @PVince81 @patrickjahns - pls provide your input.

**Comment by IljaN** [comment]
@settermjd Could you please dump a full route list here as a basis for further discussion?

**Comment by settermjd** [comment]
```
+-----------------------------------------------------------+-----------------+
| Path                                                      | Methods         |
+-----------------------------------------------------------+-----------------+
| /apps/encryption/ajax/adminRecovery                       | POST            |
| /apps/encryption/ajax/changeRecoveryPassword              | POST            |
| /apps/encryption/ajax/getStatus                           | GET             |
| /apps/encryption/ajax/setEncryptHomeStorage               | POST            |
| /apps/encryption/ajax/updatePrivateKeyPassword            | POST            |
| /apps/encryption/ajax/userSetRecovery                     | POST            |
| /apps/federatedfilesharing/                               | GET             |
| /apps/federatedfilesharing/notifications                  | POST            |
| /apps/federatedfilesharing/personalsettings/setuserconfig | POST            |
| /apps/federatedfilesharing/shares                         | POST            |
| /apps/federation/auto-add-servers                         | POST            |
| /apps/federation/trusted-servers                          | POST            |
| /apps/federation/trusted-servers/{id}                     | DELETE          |
| /apps/files/                                              | GET             |
| /apps/files/ajax/download.php                             |                 |
| /apps/files/ajax/getstoragestats.php                      |                 |
| /apps/files/ajax/list.php                                 |                 |
| /apps/files/api/v1/files/{path}                           | POST            |
| /apps/files/api/v1/showhidden                             | POST            |
| /apps/files/api/v1/sorting                                | POST            |
| /apps/files/api/v1/thumbnail/{x}/{y}/{file}               | GET             |
| /apps/files/download{file}                                |                 |
| /apps/files_external/ajax/oauth1.php                      |                 |
| /apps/files_external/ajax/oauth2.php                      |                 |
| /apps/files_external/ajax/public_key.php                  | POST            |
| /apps/files_external/applicable                           |                 |
| /apps/files_external/globalstorages                       | GET,POST        |
| /apps/files_external/globalstorages/{id}                  | DELETE,GET,PUT  |
| /apps/files_external/userglobalstorages                   | GET,POST        |
| /apps/files_external/userglobalstorages/{id}              | DELETE,GET,PUT  |
| /apps/files_external/userstorages                         | GET,POST        |
| /apps/files_external/userstorages/{id}                    | DELETE,GET,PUT  |
| /apps/files_sharing/ajax/list.php                         |                 |
| /apps/files_sharing/ajax/publicpreview.php                |                 |
| /apps/files_sharing/api/externalShares                    | GET,POST        |
| /apps/files_sharing/api/externalShares/{id}               | DELETE,GET,PUT  |
| /apps/files_sharing/external                              |                 |
| /apps/files_sharing/personalsettings/setuserconfig        | POST            |
| /apps/files_sharing/publicpreview                         |                 |
| /apps/files_sharing/shareinfo                             |                 |
| /apps/files_sharing/testremote                            | GET             |
| /apps/files_texteditor/ajax/loadfile                      | GET             |
| /apps/files_texteditor/ajax/savefile                      | PUT             |
| /apps/files_trashbin/ajax/delete.php                      |                 |
| /apps/files_trashbin/ajax/isEmpty.php                     |                 |
| /apps/files_trashbin/ajax/list.php                        |                 |
| /apps/files_trashbin/ajax/preview.php                     |                 |
| /apps/files_trashbin/ajax/undelete.php                    |                 |
| /apps/gallery/                                            | GET             |
| /apps/gallery/api/config                                  | GET             |
| /apps/gallery/api/files/download/{fileId}                 | GET             |
| /apps/gallery/api/files/list                              | GET             |
| /apps/gallery/api/gallery/{folderId}                      | GET             |
| /apps/gallery/api/preview/{fileId}/{width}/{height}       | GET             |
| /apps/gallery/api/thumbnails                              | GET             |
| /apps/gallery/api/{path}                                  | OPTIONS         |
| /apps/gallery/config                                      | GET             |
| /apps/gallery/config.public                               | GET             |
| /apps/gallery/error                                       | GET,POST        |
| /apps/gallery/files.public/download/{fileId}              | GET             |
| /apps/gallery/files.public/list                           | GET             |
| /apps/gallery/files/download/{fileId}                     | GET             |
| /apps/gallery/files/list                                  | GET             |
| /apps/gallery/preview.public/{fileId}                     | GET             |
| /apps/gallery/preview/{fileId}                            | GET             |
| /apps/gallery/s/{token}                                   | POST            |
| /apps/gallery/s/{token}/{filename}                        | GET             |
| /apps/gallery/slideshow                                   | GET             |
| /apps/gallery/thumbnails                                  | GET             |
| /apps/gallery/thumbnails.public                           | GET             |
| /apps/templateeditor/settings/mailtemplate                | DELETE,GET,POST |
| /apps/updatenotification/channel                          | POST            |
| /apps/updatenotification/credentials                      | GET             |
| /avatar/                                                  | DELETE,POST     |
| /avatar/cropped                                           | POST            |
| /avatar/tmp                                               | GET             |
| /core/ajax/appconfig.php                                  |                 |
| /core/ajax/share.php                                      |                 |
| /core/ajax/update.php                                     |                 |
| /core/js/oc.js                                            |                 |
| /core/search                                              |                 |
| /cron                                                     | GET             |
| /displaynames                                             | POST            |
| /f/{fileId}                                               |                 |
| /heartbeat                                                |                 |
| /login                                                    | GET,POST        |
| /login/challenge/{challengeProviderId}                    | GET,POST        |
| /login/selectchallenge                                    | GET             |
| /logout                                                   | GET             |
| /lostpassword/email                                       | POST            |
| /lostpassword/reset/form/{token}/{userId}                 | GET             |
| /lostpassword/set/{token}/{userId}                        | POST            |
| /occ/{command}                                            | POST            |
| /ocs/apps/files_external/api/v1/mounts                    | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares              | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares/pending      | GET             |
| /ocs/apps/files_sharing/api/v1/remote_shares/pending/{id} | DELETE,POST     |
| /ocs/apps/files_sharing/api/v1/remote_shares/{id}         | DELETE,GET      |
| /ocs/cloud/apps                                           | GET             |
| /ocs/cloud/apps/{appid}                                   | DELETE,GET,POST |
| /ocs/cloud/groups                                         | GET,POST        |
| /ocs/cloud/groups/{groupid}                               | DELETE,GET      |
| /ocs/cloud/groups/{groupid}/subadmins                     | GET             |
| /ocs/cloud/users                                          | GET,POST        |
| /ocs/cloud/users/{userid}                                 | DELETE,GET,PUT  |
| /ocs/cloud/users/{userid}/disable                         | PUT             |
| /ocs/cloud/users/{userid}/enable                          | PUT             |
| /ocs/cloud/users/{userid}/groups                          | DELETE,GET,POST |
| /ocs/cloud/users/{userid}/subadmins                       | DELETE,GET,POST |
| /ocs/config                                               | GET             |
| /ocs/person/check                                         | POST            |
| /ocs/privatedata/deleteattribute/{app}/{key}              | POST            |
| /ocs/privatedata/getattribute                             | GET             |
| /ocs/privatedata/getattribute/{app}                       | GET             |
| /ocs/privatedata/getattribute/{app}/{key}                 | GET             |
| /ocs/privatedata/setattribute/{app}/{key}                 | POST            |
| /ocsapp/apps/federation/api/v1/request-shared-secret      | POST            |
| /ocsapp/apps/federation/api/v1/shared-secret              | GET             |
| /ocsapp/apps/files_sharing/api/v1/notification/marksent   | POST            |
| /ocsapp/apps/files_sharing/api/v1/notification/send       | POST            |
| /ocsapp/apps/files_sharing/api/v1/sharees                 | GET             |
| /ocsapp/apps/files_sharing/api/v1/shares                  | GET,POST        |
| /ocsapp/apps/files_sharing/api/v1/shares/pending/{id}     | DELETE,POST     |
| /ocsapp/apps/files_sharing/api/v1/shares/{id}             | DELETE,GET,PUT  |
| /ocsapp/cloud/capabilities                                | GET             |
| /ocsapp/cloud/shares                                      | POST            |
| /ocsapp/cloud/shares/{id}/accept                          | POST            |
| /ocsapp/cloud/shares/{id}/decline                         | POST            |
| /ocsapp/cloud/shares/{id}/permissions                     | POST            |
| /ocsapp/cloud/shares/{id}/reshare                         | POST            |
| /ocsapp/cloud/shares/{id}/revoke                          | POST            |
| /ocsapp/cloud/shares/{id}/unshare                         | POST            |
| /ocsapp/cloud/user                                        | GET             |
| /ocsapp/ocm-provider                                      | GET             |
| /s/{token}                                                |                 |
| /s/{token}/authenticate                                   | GET,POST        |
| /s/{token}/download                                       | GET             |
| /settings/admin                                           | GET             |
| /settings/admin/certificate                               | POST            |
| /settings/admin/certificate/{certificateIdentifier}       | DELETE          |
| /settings/admin/legal/imprint                             | POST            |
| /settings/admin/legal/privacypolicy                       | POST            |
| /settings/admin/log/download                              | GET             |
| /settings/admin/log/level                                 | POST            |
| /settings/admin/mailsettings                              | POST            |
| /settings/admin/mailsettings/credentials                  | POST            |
| /settings/admin/mailtest                                  | POST            |
| /settings/ajax/checksetup                                 | GET             |
| /settings/ajax/disableapp.php                             |                 |
| /settings/ajax/enableapp.php                              |                 |
| /settings/ajax/excludegroups.php                          |                 |
| /settings/ajax/navigationdetect.php                       |                 |
| /settings/ajax/setlanguage.php                            |                 |
| /settings/ajax/uninstallapp.php                           |                 |
| /settings/ajax/updateapp.php                              |                 |
| /settings/apps/list                                       | GET             |
| /settings/domains                                         | GET,POST        |
| /settings/domains/{id}                                    | DELETE          |
| /settings/integrity/failed                                | GET             |
| /settings/integrity/rescan                                | GET             |
| /settings/mailaddress/change/{token}/{userId}             | GET             |
| /settings/personal                                        | GET             |
| /settings/personal/authtokens                             | GET,POST        |
| /settings/personal/authtokens/{id}                        | DELETE,GET,PUT  |
| /settings/personal/certificate                            | POST            |
| /settings/personal/certificate/{certificateIdentifier}    | DELETE          |
| /settings/personal/changepassword                         | POST            |
| /settings/users/groups                                    | GET             |
| /token/generate                                           | POST            |
+-----------------------------------------------------------+-----------------+
```

**Comment by settermjd** [comment]
After a quick discussion with @IljaN, I've added a short "further reading" section to the PR. The decision was that this is a good start, which we can build upon in the future. @pmaier1 @PVince81, are you happy with this approach and PR?

**Pull request merged**
