### PR TITLE
redis address correction

### PR DESCRIPTION
**Pull request by voroyam**
the ip address in the example was machine specific. replaced it with the loop back address.

### CODE REVIEW

**Comment by settermjd** [comment]
@voroyam, are you happy with the additional changes that I've made?

**Comment by voroyam** [comment]
> Looks like a good time to use two of the site-wide attributes: `oc-examples-server-url` and `std-port-redis` (in site.yml), instead of hard-coded values.

would you mind linking to the site.yml or at least writing here what the values of those variables are so people don't have to do it themselves?

If you are changing the page, you are doing that anyway, right?

The site.yml is a long page with small text, so reading through the entire bottom half with long variable names is not a pleasure that I want to repeat.

**Comment by voroyam** [comment]
> @voroyam, are you happy with the additional changes that I've made?

Not really. The redis port won't change anytime soon, so I don't see the point behind replacing 4 didgets with a longer variable name.

The host has to be the IP-address, not the server URL. At least this is my understanding.

**Comment by settermjd** [comment]
> > @voroyam, are you happy with the additional changes that I've made?
> 
> Not really. The redis port won't change anytime soon, so I don't see the point behind replacing 4 didgets with a longer variable name.
> 
> The host has to be the IP-address, not the server URL. At least this is my understanding.

Thanks for the clarification.

**Comment by voroyam** [comment]
LGTM

**Comment by voroyam** [comment]
@settermjd can you review this and merge?

**Comment by settermjd** [comment]
Just created PRs to backport it to 10.2, 10.1, & 10.0. All should be merged in the next 30 mins.

**Pull request merged**
