### PR TITLE
New metrics features

### PR DESCRIPTION
**Pull request by EParzefall**
Added information on how to disable the dashboard, fixes issue #4207.
Download buttons now for system view and user view available, plus separate cvs downloads, fixes issue #4208.

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by mmattel** [comment]
I guess that there is no backport necessary - or?

**Comment by EParzefall** [comment]
@JanAckermann Do we need backports to 10.8 and 10.7 docs?

**Review by JanAckermann — APPROVED** [review]
LGTM 👍

**Comment by JanAckermann** [comment]
This runs completely detached from core. I would do a Backport. 

BUT, metrics app 1.1.0 has NOT yet release, so I would stale this PR until it is done

**Comment by EParzefall** [comment]
Okay, thanks, changed to draft to avoid accidental merge.

**Comment by JanAckermann** [comment]
Thank you, I will keep an open eye on the progress and ping you as we are about to release metrics 1.1.0

**Comment by mmattel** [comment]
> This runs completely detached from core. I would do a backport.

👍 just checked, metrics is available in 10.8 and 10.7

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
