### PR TITLE
Fixing missing attribute warnings

### PR DESCRIPTION
**Pull request by mmattel**
This was a hell of a ride...

Fixing https://github.com/owncloud/docs/issues/3107 (asciidoctor: WARNING: skipping reference to missing attribute: base_uri)

During the search why there are missing attribute warnings I identified many issues related and fixed them:
* The playbook did not contain all necessary parameters for local builds to update external docs from client, ios ect
* It also did not contain a parameter necessary to render some conditional content when building the docs locally
* Variable namings for the same thing in scripts were not unified
* The use of common attributes for scripts was one time present and one time not
* ruby scripts had errors 
* A bunch of orphaned script files
* Wrong script references
* **AND MOST IMPORTANT** found the reason for missing attribute warnings. After fixing all the details above, the warnings came from rendering the branches where the attributes were not fixed (of course not...). This leaded to a improved build description and a how-to find and fix those issues 😄 

Backport to 10.6 and 10.5 necessary

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
Only tiny things. This looks great!

**Review by mschreml — APPROVED** [review]

**Comment by mschreml** [comment]
Can I merge and backport? @mmattel

**Comment by phil-davis** [comment]
Just a moment, I will apply my small review changes and then squash...

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Done - can be merged when CI finishes again.

**Pull request merged**
