### PR TITLE
[WIP] Initial documentation of how to set up Office Online Server

### LINKED ISSUE #2266: Document the setup of OfficeOnline
Currently, only @DeepDiver1975 knows how to configure it.

## What Needs to be Documented?
Setup of an OfficeOnline Server

## Where Does This Need To Be Documented?
Admin Docs

## Why Should This Change Be Made? (Optional)
Not existing.

## What Type Of Content Change Is This? (Optional)
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #2266.

### CODE REVIEW

**Comment by settermjd** [comment]
@voroyam I need your help/input to complete this PR, pls.

**Comment by voroyam** [comment]
@settermjd could you explain the background of this PR?

We have it already documented in the internal docs. But documenting it in the official docs seems wrong.

**Comment by micbar** [comment]
@voroyam I totally agree.

**Comment by settermjd** [comment]
It was requested in #2266.

**Pull request closed without merging**
