### PR TITLE
[10.4] [PR 2320] Update system_requirements.adoc

### PR DESCRIPTION
**Pull request by mmattel**
Backport of PR #2320

### CODE REVIEW

**Comment by HanaGemela** [comment]
@mmattel thank you

**Comment by phil-davis** [comment]
@HanaGemela should this also be done to `10.3` docs branch?

I guess this client support applies like this also when the server is running 10.3.2

**Comment by HanaGemela** [comment]
@phil-davis yes, this also applies to 10.3

**Comment by phil-davis** [comment]
@mmattel are you happy to do a backport to 10.3, and then I can easily approve/merge.

**Pull request merged**
