### PR TITLE
Add Running occ command section to admin_manual/pages/installation/docker/index.adoc

### PR DESCRIPTION
**Pull request by JanAckermann**
This PR will guide how to run occ commands proper in a docker environment

### CODE REVIEW

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
Backports:
10.6 #3073 
10.5 #3074

**Comment by mmattel** [comment]
@JanAckermann 
Q: `docker-compose exec owncloud occ <command>`
usually, an occ command needs to be run as webserver user (eg www-data). This is not noted here. Is this intentionally or not needed ... (can you explain)? In any case it would be good to have a note about it.

**Comment by mmattel** [comment]
@JanAckermann Ping...

**Comment by JanAckermann** [comment]
@mmattel Let me check

**Pull request merged**
