### PR TITLE
update docker compose file and instructions

### PR DESCRIPTION
**Pull request by xoxys**
As the webhippie containers are outdated and not maintained anymore we should not recommend it. Switched to official containers and updated instructions.

### CODE REVIEW

**Comment by mmattel** [comment]
This superseeds https://github.com/owncloud/docs/pull/3469 which I am closing now.

**Comment by mmattel** [comment]
I will do a render check and approve if ok.

Backport to 10.6 and 10.7

**Comment by xoxys** [comment]
Sorry didn't searched for existing PR's

**Comment by mmattel** [comment]
> Sorry didn't searched for existing PR's

The referenced PR had only a subset of your changes, so totally fine creating a new and complete one.

**Comment by xoxys** [comment]
What about https://doc.owncloud.com/server/10.7/developer_manual/general/devenv_docker.html? Seems to be outdated and is not linked in the nav?

**Comment by xoxys** [comment]
IMO we should remove this file. Two years old without an update and nearly all links/referenced files dead but we can of course separate it into a standalone PR.

**Comment by mmattel** [comment]
> IMO we should remove this file. Two years old without an update and nearly all links/referenced files dead but we can of course separate it into a standalone PR.

I can remove it in this PR if you want and the cleanup is done. The alternative would be to bring it up to date and add it to the nav - in a separate PR. I am not a docker specialist, so I would need help to do that.

**Comment by xoxys** [comment]
As this is a designed to be a dev environment I could not help much as I don't know what's required. Maybe someone from the engineering team knows more, maybe it exists a working compose dev setup already somewhere.

**Comment by mmattel** [comment]
I will keep the file in for the time being and get a specialist to ask for support

**Comment by mmattel** [comment]
@xoxys I guess that there is something wrong in the line:
`/usr/bin/entrypoint /usr/b`
either `/usr/b` should be removed (missing what?) or completed
Pls advise

**Comment by xoxys** [comment]
No thats the original output. The "..." means it is just shortened.

**Comment by xoxys** [comment]
Its just a copy/paste of the original output from the docker-compose ps command.

**Comment by mmattel** [comment]
Fixed some changes in index.adoc, made a proper table out of the manual created table and fixed some additional things I found. If you are fine, I can approve, merge and backport.
Regarding backport, beside 10.7, ist this also for 10.6 (I guess yes but not sure)

**Comment by xoxys** [comment]
Cool thanks. Yes please backport to 10.6 and 10.7

**Review by mmattel — APPROVED** [review]

**Pull request merged**
