### PR TITLE
[2326] Update deployment recommendations example for finding the PHP session.save_path value

### LINKED ISSUE #2326: installation/deployment_recommendations.adoc needs a update
## What Needs to be Documented?

`installation/deployment_recommendations.adoc` needs a update, see comments in https://github.com/owncloud/docs/pull/2321#pullrequestreview-361023746

## Why Should This Change Be Made? (Optional)
Scripts are out of date,
URL´s need to be changed to macro definition

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [x] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@JKawohl @enbrnz @settermjd

### PR DESCRIPTION
**Pull request by settermjd**
This change replaces the existing examples showing how to retrieve the `session.save_path` value with a small awk/bash one-liner that works for PHP 7.3. This fixes #2326. **Please note:** b34d1cd is a cleanup commit, nothing more.

### CODE REVIEW

**Comment by mmattel** [comment]
I would recommend for additional cleanup to rewrite all external links to the example scheme as follows: `{mariadb-monitor-url}[MariaDB Monitor]`
as we do in all other documents

**Comment by settermjd** [comment]
> I would recommend for additional cleanup to rewrite all external links to the example scheme as follows: `{mariadb-monitor-url}[MariaDB Monitor]`
> as we do in all other documents

@mmattel, that change has now been made. I completed it throughout the document, which is outside the scope of this PR, to be fair. But, it seemed like the correct choice at the time.

**Comment by mmattel** [comment]
The only thing that could be improved

**Comment by mmattel** [comment]
Sorry, pressed the wrong button...

**Pull request merged**
