### PR TITLE
Fix Antora compile warning missing reference to latest-download-version

### PR DESCRIPTION
**Pull request by mmattel**
Fixing a compile warning because of a missing reference.
Creating the proper reference in site.yml

Attn: Backport to 10.5 ONLY !

We can do a BP to 10.4 too, but...
...then we have to do a pick of `manual_upgrade.adoc` and fix `site.yml` in 10.4 (add `latest-download-version: 10.5.0`). The other content in site.yml in 10.4 stays the same !

@phil-davis your help is appreciated :smile:

### CODE REVIEW

**Comment by phil-davis** [comment]
This looks good for fixing that hard-coded `10.2.1`

But I don't see where `latest-download-version` is already mentioned in the docs repo. How did Antora give a compile warning?

**Comment by mmattel** [comment]
When you run `yarn run antora` you get compile warnings like:
`asciidoctor: WARNING: skipping reference to missing attribute: latest-download-version`
Then doing a grep you find the document with the attribute used.
The good thing is, it is working fine for master and 10.5
The challenge is, site.yml in 10.4 is slightly different so you cant easily BP it. You have to fix it as described above... 😢

**Comment by mmattel** [comment]
approve and merge?

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
@mmattel can you make a backport please?

**Pull request merged**
