### PR TITLE
removed legacy content

### PR DESCRIPTION
**Pull request by voroyam**
removed legacy content

inspired by:

https://github.com/owncloud/docs/issues/250

### CODE REVIEW

**Comment by tboerger** [comment]
This option have been removed?

**Comment by voroyam** [comment]
> This option have been removed?

Apparently this never worked in enterprise and sometimes in community, but since no one we know has this option, make sense to remove it from the docs.

**Comment by tboerger** [comment]
I guess we got it within the base docker image, need to check that

**Comment by voroyam** [comment]
> I guess we got it within the base docker image, need to check that

Have you ever used that? :)

**Comment by tboerger** [comment]
We offer the option via env variable if it's documented within the sample config on core repository :)

**Pull request merged**
