### PR TITLE
Adjust the Provisioning API

### PR DESCRIPTION
**Pull request by JanAckermann**
* The Provisioning API should be located under developer_manual/core/apis
* The navigation item 'User Provisioning API' at admin_manual/configuration/user/ should link to this page to section #instruction-set-for-users
* A important note that the given user must be an admin or sub-admin should be displayed

### CODE REVIEW

**Comment by mmattel** [comment]
@JanAckermann mid ping me on talk?

**Comment by JanAckermann** [comment]
@mmattel going for a dog walk now, after, for sure

**Comment by JanAckermann** [comment]
@mmattel hanging arround here: 
https://global.gotomeeting.com/join/495499221

**Comment by mmattel** [comment]
I am in, seen too late...

**Pull request closed without merging**
