### PR TITLE
Improved installation manual.

### PR DESCRIPTION
**Pull request by voroyam**
Updated server version

Removed permissions script which caused confusion and troubles.

### CODE REVIEW

**Comment by voroyam** [comment]
> I guess the actual script `installation/ubuntu/18.04/finalise-install.sh` should also be deleted from the repo.

done

**Comment by voroyam** [comment]
thanks for the review @micbar

**Comment by voroyam** [comment]
This has to be backported to the relevant branches.

**Comment by phil-davis** [comment]
Backports to all 4 old branches done.
Needs to be backported that far so that the script really gets removed from everywhere.

**Pull request merged**
