### PR TITLE
Use tabs only when rendering content in HTML format

### PR DESCRIPTION
**Pull request by settermjd**
This change is being made as there are build errors when generating PDF versions of the documentation because of the misunderstood tab formatting.

### CODE REVIEW

**Comment by voroyam** [comment]
No idea what this is.

**Comment by settermjd** [comment]
I'll add some screenshots.

**Comment by voroyam** [comment]
As far as I can see these changes are in the dev manual, I have no idea about this manual. But if no one else is going to approve this PR I trust you know what you are doing. Approved.

**Comment by settermjd** [comment]
Just realised that I merged it too quickly. I need to update the drone build script.

**Comment by settermjd** [comment]
Not going to backport it until a follow-up PR is finished.

**Pull request merged**
