### PR TITLE
update npm elasticsearch to version 16.4.0

### PR DESCRIPTION
**Pull request by settermjd**

### CODE REVIEW

**Comment by tboerger** [comment]
As I'm not building the docs locally so far I can't say if that breaks anything.

**Comment by settermjd** [comment]
Any suggestions for moving-forward on this?

**Comment by tboerger** [comment]
Make sure that it works and merge it 🤷‍♂

**Comment by settermjd** [comment]
I don't have Drone running locally. Any guide on how to do that?

**Comment by tboerger** [comment]
No need for drone. Just use some elasticsearch instance and set the required env variables

**Comment by settermjd** [comment]
Closing. Using dependencybot instead.

**Pull request closed without merging**
