### PR TITLE
apache 2.4: updated redirect rule

### PR DESCRIPTION
**Pull request by thommierother**

### CODE REVIEW

**Comment by mmattel** [comment]
@thommierother thanks for the PR. Mind to add a description what the change is about?

**Comment by thommierother** [comment]
mod_rewrite and the "rewrite" rules operate on the Server-side. mod_alias and "redirect" simply asks the client to refetch with the new URI.  mod_rewrite is recommended as "last resort" but not needed for such a simple case. See https://httpd.apache.org/docs/trunk/rewrite/avoid.html and https://httpd.apache.org/docs/trunk/mod/mod_alias.html#redirect for reference

**Comment by mmattel** [comment]
I cant make a suggestable commit, so you need to do, but on line 111 you also need to fix the text from `RewriteRule` -- `Redirect`.

**Comment by mmattel** [comment]
Huuu...
I was just reading the whole document especially the content below the changes, which reads the following. The keywords are `not to use redirect rules...violate the OpenID Connect specification`:

Here is the complete statement:

**TIP:** `Depending on the respective infrastructure setup there can be other ways to solve this. In any case, please make sure not to use redirect rules as this will violate the OpenID Connect specification.`

If your change is correct, please prove not violating the secs.

**Comment by thommierother** [comment]
Interesting. I can not find any info that the OIDC spec **forbids** usage of "redirect 301" instead of a rewrite rule on the web-server side and in the context of the clients service discovery information (./well-known ... URI) . We use "redirect 301" in the OIDC configs at our customers infrastructure too. Without issues, but with another client software (java-based).

**Comment by mmattel** [comment]
> I can not find any info that the OIDC spec forbids usage of "redirect 301" instead of a rewrite rule on the web-server side and in the context of the clients service discovery information (./well-known ... URI).

Will have a look asap, pls be patient...

**Comment by thommierother** [comment]
I know that the redirect is not recommended in cases where we already have a security context with personal data/token data. But in this case it is only the first service discovery - this shouldnt be a problem ... Maybe @DeepDiver1975 knows more ...

**Comment by DeepDiver1975** [comment]
Our clients are not accepting a 301 due to the mentioned security impact. Maybe not mandatory by the specs - but by us ;-)

**Comment by thommierother** [comment]
thanks for clarification, in this case my PR is obsolete

**Comment by thommierother** [comment]
closed, as the change would violate OC specs

**Pull request closed without merging**
