### PR TITLE
Rename make test-php to test-php-unit

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #660 

due to core PR https://github.com/owncloud/core/pull/34638

### CODE REVIEW

**Comment by phil-davis** [comment]
@settermjd this is an interesting case for what to backport.

For changes to the ongoing day-to-day developer environment, we want the developers to be able to find the up-to-date documentation. But we do not want to backport this to `10.1` because actually if a developer checks out the `v10.1.0` tag and tries to `make test-php-unit` then it will not work.

So in this case we do want the "master" documentation to be findable online.

**Comment by mmattel** [comment]
Is backporting required ?

**Comment by phil-davis** [comment]
If you are a developer and have actually chcked out a 10.1 or 10.0 branch:
```
git checkout v10.1.0
git checkout v10.0.10
```
then you have to use the previous `make test-php` to run the unit tests.

If you are using a current in-development branch (which developers will be doing 99% of the time):
```
git checkout stable10
git checkout master
```
then you have to type `make test-php-unit` 

This is an example where we do not backport, but where the "current fluid docs master" needs to be published so that developers can see doc of the current development environment. And developers need to understand that they should usually look at "docs master" when reading developer docs.

**Comment by mmattel** [comment]
Your text is very clear and informative.
Could this be somehow adopted to be a unified text for all doc branches?
That would be imho very helpful and would avoid confusion - or?

**Pull request merged**
