### PR TITLE
IE11 deprecation note

### PR DESCRIPTION
**Pull request by pako81**
Added planned IE11 deprecation for next core version in the 10.13 Release Notes.

### CODE REVIEW

**Comment by mmattel** [comment]
Question just to be precise:
* It is already dropped because of dependency upgrades in 10.13
* or it will be dropped with the next release AFTER 10.13 because of upcoming dependency upgrades?

**Review by phil-davis — APPROVED** [review]
LGTM. This means that we still support IE11 for running the classic web UI with an ownCloud 10.13.0 server.

But 10.14.0 will not support IE11 (some things might still work, but no guarantee)

**Comment by pako81** [comment]
We have seen that the JS dependencies updates done in 10.13 already broke things in core in combination with IE11 (and possible in other apps where they have been applied as well?). For this reason, as of 10.14.0/11 IE11 support will be discontinued.

**Comment by mmattel** [comment]
For me this sounds quite strange:
`We have seen that the JS dependencies updates done in 10.13 already broke things in core in combination with IE11 (and possible in other apps where they have been applied as well?)`
Which means we support a browser where stuff is already broken for this browser.

Imho, an additional release note would be good that tells that already some IE11 things might not be fully functional due to necessary dependeny upgrades made in 10.13

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/pull/40934 fixed an IE11 problem in core.
files_mediaviewer is a "newer" app and has always been known to not be supported on IE11.

IMO there are no more known issues in core 10.13 with IE11. So we can continue to support it for this release.
Is anyone else aware of another IE11 problem?

**Comment by hodyroff** [comment]
The notice is forward looking, always was. Yes, we fixed an issue for IE11 in 10.13 now, therefor we decided to do the depreciation warning for the next version. If we find 10.14 works, we still have an out and can continue to support.

**Review by mmattel — APPROVED** [review]

**Pull request merged**
