### PR TITLE
merge occ commands

### PR DESCRIPTION
**Pull request by voroyam**
merging the app occ commands and the core occ commands.

### CODE REVIEW

**Comment by mmattel** [comment]
@voroyam I have take a look into, but there is some work up to the next review, you need to ...
1) create two main overview sections
- core commands (eg == Core Related Commands)
do this before the first core commands are described
- app commands  (eg == App Related Commands)
do this before the first app commands are described
2) set toclevels to 2
this will show the overview and all commands related to each section (but not subsections)
3) move all corresponding sections one level deeper (means == becomes === ect)
3) remove the second toc in the apps section
only one toc allowed...
4) remove double description text in the new apps section (it is already above core)

**Comment by voroyam** [comment]
sorry, a typo in your name :) It should have been martin ofc.

**Comment by voroyam** [comment]
@mmattel @settermjd can you review this?

**Comment by mmattel** [comment]
@voroyam with commit `correct levels`, I fixed the heading levels.
We show now three main levels and all main commands underneath.
The details under the commands are as discussed not in the toc.
Please prove this by pulling and render it via a adoc browser plugin.

From my pov this is ready to be approved.

Suggestion: **to be done in an additional PR**, we can reorder commands as they are not ordered correctly.

**Comment by mmattel** [comment]
Removed: `occ_app_command.adoc`
Fixed: `nav.adoc`
Fixed: double LDAP ID

Ready to review and approval / merge

**Pull request merged**
