### PR TITLE
[WIP] Update Issue Templates

### PR DESCRIPTION
**Pull request by settermjd**
This PR proposes two new templates when creating documentation issues, ones that are more specific and easier for users to use.

### CODE REVIEW

**Comment by settermjd** [comment]
For all the reviewers, I'm proposing to add these two new issue templates with the hope that creating issues will be easier, clearer, and more transparent, as I'm aiming to make the docs more responsive.

**Comment by voroyam** [comment]
I am confused, what template will be there if I click on Create new issue? How can there be 2?

**Comment by settermjd** [comment]
@voroyam, still working on that.

**Comment by voroyam** [comment]
I have no idea what you are trying to acheive here = can't review this. 

My original Idea for the issue template was simple and short: What, Where, How. 

I still think that it's the best one.

**Pull request closed without merging**
