### PR TITLE
Update saml_2.0_sso.adoc

### PR DESCRIPTION
**Pull request by ChrisEdS**
Add a dash to `sudo apt-get install libapache2-mod-shib2`

### CODE REVIEW

**Comment by voroyam** [comment]
please add the info where this change should be back ported to. (which branches)

**Review by voroyam — APPROVED** [review]

**Comment by mmattel** [comment]
pls add a note for backporting and do post merging

**Review by phil-davis — COMMENTED** [review]
Should all the `mod_shib` on this page be changed to `mod-shib`

For example, the heading:
```
SAML 2.0 Based SSO with Active Directory Federation Services (ADFS) and mod_shib
```

```
SAML 2.0 Based SSO with Active Directory Federation Services (ADFS) and mod-shib
```

???

Is this thing known as `mod_shib` or `mod-shib` ?

**Comment by mschreml** [comment]
@ChrisEdS done!

backports:

master - #3344
10.6 - #3345

**Pull request merged**
