### PR TITLE
Remove apt install software-properties-common

### PR DESCRIPTION
**Pull request by ho4ho**
Seen #2190 remove `add-apt-repository` but `apt install software-properties-common` only required by `add-apt-repository` so remove also.

### CODE REVIEW

**Comment by ho4ho** [comment]
Not sure by this:

> First, ensure ... and that PHP 7.3 is available in the APT repository. 

Commands never helped ensure PHP 7.3 is available. Remove 7.3 text fully?

**Comment by mmattel** [comment]
This is quite interesting...

To my knowledge php7.3 is not default available in Ubuntu 18.04
Therefore you have to use:
```
apt install software-properties-common && \
  add-apt-repository ppa:ondrej/php && \
```
After googling, I made a double check on my system:
```
sudo apt install php7.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.3
E: Couldn't find any package by glob 'php7.3'
E: Couldn't find any package by regex 'php7.3'

sudo apt install libapache2-mod-php7.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libapache2-mod-php7.3
E: Couldn't find any package by glob 'libapache2-mod-php7.3'
E: Couldn't find any package by regex 'libapache2-mod-php7.3'
```
For a second double check run:
`sudo apt-cache search php7`
You will not get any php7.3 results!

**Finding:**
Revert https://github.com/owncloud/docs/pull/2190 and it´s backports and close this PR

@settermjd

**Comment by ho4ho** [comment]
But Ubuntu 18.04 use PHP 7.2 so need 7.3 really? https://packages.ubuntu.com/bionic/php7.2

**Comment by mmattel** [comment]
The installation instruction of this document tells about installing php7.3 (see below)
Which is not a bad idea as 7.3 outperforms 7.2 by about 10-15%
But of course you just can install default 7.2 ...
But this would be a different/completely rewritten PR.

```
Install the Required Packages
apt install -y \
  apache2 \
  libapache2-mod-php7.3 \
  mariadb-server \
  openssl \
  php-imagick php7.3-common php7.3-curl \
  php7.3-gd php7.3-imap php7.3-intl \
  php7.3-json php7.3-mbstring php7.3-mysql \
  php-ssh2 php7.3-xml php7.3-zip \
  php-apcu php-redis redis-server \
  wget
```

**Comment by settermjd** [comment]
I'll review the instructions around this in an additional PR.

**Comment by mmattel** [comment]
@settermjd pls carefully read my comments.
These say, if you remove the two prerequisites,
one already has been removed by the referenced PR´s,
The other one will be removed by this PR
you CAN NOT install php7.3...

See also my advice about this and the referenced PR.

**Comment by mmattel** [comment]
Merging was not good. 👎 
Now you have to reimplement the prerequisite commands again

**Comment by settermjd** [comment]
That's not necessary, as the decision was made internally to not reference a specific version of PHP, but defer to the default.

**Comment by phil-davis** [comment]
It does need the mention of PHP 7.3 in the text to be removed.

**Comment by settermjd** [comment]
> It does need the mention of PHP 7.3 in the text to be removed.

Doing that in #2216.

**Pull request merged**
