### PR TITLE
 [10.3] [PR 2316] Redirect the external storage configuration to the relevant occ commands

### PR DESCRIPTION
**Pull request by settermjd**
Backports #2316.

### CODE REVIEW

**Comment by phil-davis** [comment]
Fails CI somehow - https://drone.owncloud.com/owncloud/docs/7193/1/4

**Comment by settermjd** [comment]
> Fails CI somehow - https://drone.owncloud.com/owncloud/docs/7193/1/4

Looking into that now.

**Comment by settermjd** [comment]
It fails because there was still a link in the admin manual's navigation file to the external storage configuration documentation file, which was deprecated in the original PR. Not sure why it only fails in this PR. Will check 10.4 and master.

**Comment by settermjd** [comment]
Turns out that I missed a final reference to the deprecated external storage configuration file. da6899b removes it. After running this, validation passes locally, so the build should pass successfully, this time.

**Pull request merged**
