### PR TITLE
Ransomware protection list updated

### PR DESCRIPTION
**Pull request by HanaGemela**
Fixes https://github.com/owncloud/docs/issues/2396

### CODE REVIEW

**Comment by mmattel** [comment]
When merged, pls backport to 10.3 and 10.4

**Comment by HanaGemela** [comment]
@mmattel I've tried to use backport.sh script and I got an error `5b4aa90 has not been merged or branch master is not pulled/rebased. Exiting`
5b4aa90 has been merged and master has been pulled. What am I doing wrong?

**Comment by mmattel** [comment]
Did you pull (and rebase) your local master after merging?
Usually you have to update your local master after a merge on GH.
Else, any changes are naturally unknown to your local copy.

**Comment by HanaGemela** [comment]
`git branch --contains 5b4aa90` returns master
So I guess the script doesn't work

**Comment by mmattel** [comment]
If you run:
`git branch --contains 5b4aa90` we get `* master`
`git branch --contains 5b4aa90 | grep -oP '(?<=\*).*'` we get ` master` (with a blank at the beginning!)
(The last code line above is from the script...)

You can try the regex `(?<=\*).*` in https://regex101.com

Have checked out master?

The `*` in the answer of `--contains` tells that a branch is checked out and the BP script only works on the checked out branch containing the commit. Therefore the grep.

Also see: https://stackoverflow.com/questions/1419623/how-to-list-branches-that-contain-a-given-commit/1419637
 
The documentation also tells:
https://doc.owncloud.com/server/latest/developer_manual/general/backporting.html
`You have checked out the branch containing the merged sha (like master)`

**Comment by mmattel** [comment]
As discussed in Talk, the cause is most likely a far outdated version of grep in macOS.
A more recent version needs to be installed via homebrew.

**Comment by HanaGemela** [comment]
Thank you, updating grep to `grep (GNU grep) 3.4` helped

**Pull request merged**
