### PR TITLE
User password cannot be "0"

### PR DESCRIPTION
**Pull request by voroyam**
In the upcoming 10.0.10 a user password cannot be set to "0".

### CODE REVIEW

**Comment by voroyam** [comment]
done. We should communicate our work better @mmattel

**Comment by mmattel** [comment]
True 😃 
Still see that the file occ_command.adoc is present with changes (not fully reverted).
If fully reverted, the file should disappear from the change list...

**Comment by mmattel** [comment]
@voroyam the easiest would be you close that PR and create a new one containing the fix for ``user_configuration.adoc``

**Comment by mmattel** [comment]
This PR is now a bit messed up, because it contains an old version of occ_command.adoc which was updated in #113 (merged). Please either do what ever is necessary that the file will not longer be in the change list (maybe rebasing) or as already suggested close that PR an create a new one which only contains the changes for the user doc.

**Comment by mmattel** [comment]
@voroyam 
Could you create a new PR containaing only the changes made in ``user_configuration.adoc`` ?

**Pull request closed without merging**
