### PR TITLE
Update links to latest docs

### PR DESCRIPTION
**Pull request by settermjd**
This change updates the home page references to the latest and previous version of the docs, and updates the component descriptor to ensure that the previous version of the docs is both built and accessible from the UI.

💁‍♂️ Do not merge until #578 is merged!

### CODE REVIEW

**Comment by tboerger** [comment]
I'm against branching every version, imho it's only maintainable to do 10.0.x and 10.1.x branches.

**Comment by settermjd** [comment]
So long as we settle on something, I'm fine with it.

**Comment by tboerger** [comment]
The client is branching as 2.5 and so on. Imho it's sufficient to do the same for the core docs

**Comment by settermjd** [comment]
Okay, I agree with you.

**Pull request closed without merging**
