### PR TITLE
Update the background jobs configuration documentation

### PR DESCRIPTION
**Pull request by settermjd**
The docs had a duplicate copy of the "_Cron Jobs_" section. This was identified in #2040. This change removes the duplicate and also fixes up the formatting of the documentation so that it follows the style guide, making it easier to maintain.

### CODE REVIEW

**Comment by voroyam** [comment]
Thanks for taking care of this issue

**Comment by settermjd** [comment]
yw.

**Comment by mmattel** [comment]
Backporting to 10.3 ?

**Comment by voroyam** [comment]
Yes, would make sense to have one consistent state.

**Pull request merged**
