### PR TITLE
[WIP] Link the appliance top-level nav item to the what is it page

### LINKED ISSUE #800: Can't link to category root
Some navigation items items don't have real links.

What_is_the_Appliance_____ownCloud_Documentation

It would be important to link to the category root. Here is an example:
https://owncloud.com/download/

Idea is to link to the Appliance section, not to the first sub-section.

BTW: The old link is broken:
https://doc.owncloud.com/server/10.1/admin_manual/appliance/

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## Which Manual Does This Relate To? (Optional)
- [x] Admin Manual
- [x] Developer Manual
- [x] User Manual
- [ ] Android
- [ ] iOS
- [x] Branded Clients
- [x] Desktop Client
- [ ] Other

/cc @haukman @MichaelvanLaar

### PR DESCRIPTION
**Pull request by settermjd**
This fixes #800. It ensures that the user can find out what the Appliance is as quickly as possible.

### CODE REVIEW

**Comment by settermjd** [comment]
@michaelstingl?

**Comment by michaelstingl** [comment]
Yeah, better now, but why `appliance/what-is-it.html` ? Wouldn't `appliance/index.html` be more robust for future content changes?

What about all the other unlinked entries in the navigation menu? Generate all the links manually?

**Comment by mmattel** [comment]
> What about all the other unlinked entries in the navigation menu?

Which other unlinked entries?
Mind to give an example?

**Comment by michaelstingl** [comment]
> Which other unlinked entries?

I'm not talking about broken links. The nav-items aren't links. They just open/close the sub-tree.

Introduction____ownCloud_Documentation

From my understanding, **all nav-items should be real links**. To help people with their ownCloud, I need to send link to the docs very often.

**Comment by settermjd** [comment]
Regarding https://github.com/owncloud/docs/pull/876#issuecomment-480602902, I'll change the name later today. Thanks for pointing that out.

**Comment by mmattel** [comment]
Pls correct me if I am wrong. What you want is, if not already present, a description (index.html) linked to each main item (like Installation, Configuration, ect) which briefly describes the topic in that section. So you can copy/paste the link and send it.

**Comment by michaelstingl** [comment]
> So you can copy/paste the link and send it.

Yes, I want to copy/paste the link and send it.

> Pls correct me if I am wrong. What you want is, if not already present, a description (index.html) linked to each main item (like Installation, Configuration, ect) which briefly describes the topic in that section.

This could be the technical solution. But I'm not the expert to propose the technical solution.

Please also see my original issue: https://github.com/owncloud/docs/issues/800

> Some navigation items items don't have real links.

(It was not only about the single "Appliance" nav item)

**Comment by settermjd** [comment]
@michaelstingl, regarding https://github.com/owncloud/docs/pull/876#issuecomment-480602902, that has now been done in 69b1e5d. Regarding https://github.com/owncloud/docs/pull/876#issuecomment-480627831, those can be changed, but they will be completed in separate PRs, to ensure that each one is as concise as possible and quick to review and approve. Thanks for suggesting these changes.

**Comment by michaelstingl** [comment]
> Regarding [#876 (comment)](https://github.com/owncloud/docs/pull/876#issuecomment-480627831), those can be changed, but they will be completed in separate PRs

Works for me 👍

**Pull request merged**
