### PR TITLE
[10.5] Document OpenID Connect

### PR DESCRIPTION
**Pull request by phil-davis**
Backport #2830 to 10.5

### CODE REVIEW

**Review by pmaier1 — APPROVED** [review]
:heart:

**Comment by mmattel** [comment]
guys, this is too early...
please follow the good practive to first merge the pr in master and then bp it to a branch.
I just have found a antory directive typo in the master pr and ...
too late - merged 😢

**Comment by pmaier1** [comment]
Sorry, we want to release tomorrow. That's why we went fastlane with this. You're absolutely right, of course. We can correct this in a follow-up PR.

**Comment by phil-davis** [comment]
we can do a follow-up PR  to `master` and then backport...

I don't know how we get around this - people want to do documentation. If there is some Antora directive typo, then CI should fail - but I realise that CI has not been setup like that. "mere mortals" are not going to know when these errors happen.

**Comment by mmattel** [comment]
> If there is some Antora directive typo, then CI should fail

the text is taken as text instead of a macro if mistyped. Therefore you have to run a compile and manually see the result. I do not see a way to overcome this...

**Comment by phil-davis** [comment]
Yes, that's more tricky. My IDE shows me the rendered output, and this problem is apparent when looking through the document. Correcting the `xref` makes it render nicely. So reviewing in the IDE seems to be an option.

**Comment by pmaier1** [comment]
There's some more to correct :/

The lists here are not working properly
- https://doc.owncloud.com/server/10.5/admin_manual/configuration/user/oidc/#setup-and-configuration
- https://doc.owncloud.com/server/10.5/admin_manual/configuration/user/oidc/#set-up-and-configure-the-identity-provider
- https://doc.owncloud.com/server/10.5/admin_manual/configuration/user/oidc/#configure-owncloud-server

Can you take care as part of the other PR?

**Comment by phil-davis** [comment]
> Can you take care as part of the other PR?

done

**Pull request merged**
