### PR TITLE
Improve makefile phony clean comment to make it clear that the pdf path is meant

### PR DESCRIPTION
**Pull request by mmattel**
This PR fixes the path for command `make clean` in makefile: `build/` --> `public/`

**Update:**
I reset the path to the original state according the comment of @tboerger below,
and updated the command description to make it more clear

### CODE REVIEW

**Comment by tboerger** [comment]
Build is the pdf output, so this previous path is totally fine.

**Comment by mmattel** [comment]
@tboerger many thanks for this. I set the path back and improved the comment.

**Comment by tboerger** [comment]
IMHO not needed at all... The Makefile is anyway only used for building the PDFs.

**Comment by mmattel** [comment]
For the sake of public knowledge, we should add that.
You know, I know now, @settermjd may now
but all the others do not know.

It is a comment improvement making things clear

**Pull request merged**
