### PR TITLE
[OC11] Issue 284 document files:scan --group

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #284 

This change should be released with the next core major version release.

So it should be able to be merged to `docs` `master`, but do not backport to any `10.*` branch because it will not be released in any of those versions.

### CODE REVIEW

**Comment by settermjd** [comment]
Having this in the documentation also highlights the point you made last week about having master be deployed to the live documentation, and being the default view. It will be confusing for users seeing features that aren't available in their release.

**Comment by PVince81** [comment]
thinking that we might want to backport this change as well as long as it's not a breaking feature @phil-davis

**Comment by phil-davis** [comment]
> Thanks for raising the issue, @phil-davis. Looks good to me. Quick question though; would it not have been simpler to implement further CSV functionality in the options supplied to group, rather than change groups to group? For example, by surrounding fields with double-quotes, as in this example, `--groups="group1",group2,group3,"group,1,2,3"` groups with and without commas in their names can be supplied to the `groups` option.

As I remember, other `occ` commands already have the repeated `--group`` way of doing it, so we kept the same system here.

**Comment by phil-davis** [comment]
> thinking that we might want to backport this change as well as long as it's not a breaking feature @phil-davis

See comment https://github.com/owncloud/core/pull/31719#issuecomment-410631045 - it breaks the old/existing way to type the `occ` command for a group scan.

**Comment by phil-davis** [comment]
> Having this in the documentation also highlights the point you made last week about having master be deployed to the live documentation, and being the default view. It will be confusing for users seeing features that aren't available in their release.

That was the reason that I made the PR now. It presses the point that we should be able to merge doc changes for core master features to docs master branch, and have it "always up-to-date and ready-to-release" (oh, I hear the pigs flying overhead again ;)

**Comment by PVince81** [comment]
hmm right :-/

**Comment by settermjd** [comment]
@phil-davis, re https://github.com/owncloud/docs/pull/642#issuecomment-467353559, I agree with you. That should be the case.

**Comment by settermjd** [comment]
On reviewing the playbook (`site.yml`) again, `master`'s been removed, so showing features for future releases is no longer an issue.

**Pull request merged**
